name: Setup Slipshow
description: Setup Slipshow, adds it to the PATH.

inputs:
  version:
    description: Which version to install
    required: false
    default: latest

runs:
  using: node24
  main: dist/index.js
