name: Hello World
description: Greet someone and record the time

inputs:
  version: # id of input
    description: Which version to install
    required: false
    default: latest

runs:
  using: node24
  main: dist/index.js
