on:
  push:
    branches:
      - main

jobs:
  compile_slipshow:
    name: Compile slipshow presentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install slipshow
        uses: panglesd/setup-slipshow@main
      - name: Create a directory if needed
        run: mkdir -p compiled
      - name: Compile presentation
        run: slipshow compile example/example.slp -o compiled/index.html
      - name: Upload as artifacts  # required for next action to publish
        uses: actions/upload-pages-artifact@v5
        with:
          path: compiled/

  # Deploy what was compiled with actions/deploy-pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: compile_slipshow
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

# See the actions/deploy-pages docs
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
