on:
  push:
    branches:
      - main

jobs:
  ubuntu_test:
    name: Testing latest on ubuntu
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install slipshow
        uses: ./ # Uses an action in the root directory

      # Use the output from the `hello` step
      - name: Try it
        run: slipshow --version

  ubuntu_fixed:
    name: Testing fixed version on ubuntu
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install slipshow
        uses: ./ # Uses an action in the root directory
        with:
          version: v0.11.0

      # Use the output from the `hello` step
      - name: Try it
        run: slipshow --version

  # hello_world_job_mac:
  #   name: A job to say hello
  #   runs-on: mac-latest

  #   steps:
  #     # To use this repository's private action,
  #     # you must check out the repository
  #     - name: Checkout
  #       uses: actions/checkout@v6

  #     - name: Hello world action step
  #       uses: ./ # Uses an action in the root directory
  #       id: hello
  #       with:
  #         who-to-greet: Mona the Octocat

  #     # Use the output from the `hello` step
  #     - name: Try it
  #       run: slipshow --version
